### ISSUE TITLE
Pausing the consumer

### ISSUE THREAD

**Issue by itamarwe** [LivePersonInc/kafka-java-bridge#10]
Is there a way to pause the consumer? Or to indicate that a message has been handled? It will allow better flow control and back-pressure.

**Comment by 1ManSmoking** [comment]
Hi Itamar,

As answered by Reem [here](https://github.com/LivePersonInc/kafka-java-bridge/issues/3), you can use start and stop methods to pause and resume the consumer.

BR,
Eli

**Comment by itamarwe** [comment]
Thanks, that's what I'm currently doing, but it has a very high overhead to start and stop the consumer. I'm just looking for something that will allow me to pause the consumer in case there's backpressure up in the pipeline.

**Comment by 1ManSmoking** [comment]
Generally you're right.
It will be more efficient to have proper pause.
Don't consider it to be critical though, so can't promise implementation.

**Comment by itamarwe** [comment]
I created a small branch in my fork.
Let me know what you think.

https://github.com/itamarwe/kafka-java-bridge/compare/feature_topicAndPartition...itamarwe:feature_pauseConsumer

**Comment by 1ManSmoking** [comment]
:) You're fast.
Took a look, didn't test yet.
Need to see what happens on shutdown while paused. 
Won't notifyAll in case of consecutive calls to pause() without resume result in unintended message reading?
Lets postpone this discussion for a few days so I will be available to integrate all your code.

Again, thanks a lot for the contribution.
Eli

**Comment by itamarwe** [comment]
1. I fixed it so it will resume on shutdown to allow the consumer to drain
2. Consecutive calls on pause are not a problem since the condition is found within a while loop. It will just block again.

I created a pull request. Feel free to go over it and comment.
https://github.com/itamarwe/kafka-java-bridge/pull/1/files

**Comment by 1ManSmoking** [comment]
Hi,

Decided against adding the pause code.
In this implementation it is possible one message may arrive even 30 min after pause.
I understand it may be a good solution for your needs, but decided not to add it to the public repository.

BR,
Eli

**Comment by itamarwe** [comment]
I think that's a shame, since the lack of flow control makes using the package impractical.

**Comment by 1ManSmoking** [comment]
There is flow control.
stop() and start().
It is slightly less efficient than internal pause.
But, it is deterministic - once you get stopped callback no more messages will be received.
That, for me, is most important.
We do handle big data with this consumer and pausing/resuming are rare operations.
In my opinion doing it too often means that you probably need to increase cluster size.

BTW, implemented the multiple topics in same consumer support.
Hope that will make your life a little easier handling multiple topics.
