### ISSUE TITLE
how do I pause or resume consumer here?

### ISSUE THREAD

**Issue by ersumitchh** [LivePersonInc/kafka-java-bridge#3]
Didn't find anything for the same.

**Comment by reemdiab** [comment]
Hey,
You can use the start and stop API for pausing and resuming.

### hlConsumer.start(cb)

Start consumer messages from kafka topic.

cb - callback is called when the consumer is started.
If callback was called with err it means consumer failed to start.

### hlConsumer.stop(cb)

Stop consuming messages.

cb - callback is called when the consumer is stopped.

**message/error events can still be emitted until stop callback is called.**

**Comment by ersumitchh** [comment]
Thanks

**Comment by itamarwe** [comment]
The problem is that it has high overhead to start and stop. I would only like to pause in case there's back pressure. Something like blocking the fetch loop. Starting and stopping has a big impact on the smoothness of my pipeline.
