### ISSUE TITLE
Unable to install using npm install kafka-java-bridge

### ISSUE THREAD

**Issue by bigbansal** [LivePersonInc/kafka-java-bridge#6]
/home/gouravbansal/Documents/Practice/nodejs/node_modules/kafka-java-bridge/scripts/postinstall.js:10
execSync("javac -cp " + javaDir + "/lib/\\* -d " + javaDir +"/out " + javaDir 
^
TypeError: undefined is not a function
    at Object.<anonymous> (/home/gouravbansal/Documents/Practice/nodejs/node_modules/kafka-java-bridge/scripts/postinstall.js:10:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
npm WARN enoent ENOENT, open '/home/gouravbansal/Documents/Practice/nodejs/package.json'
npm WARN nodejs No description
npm WARN nodejs No repository field.
npm WARN nodejs No README data
npm WARN nodejs No license field.
npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "kafka-java-bridge"
npm ERR! node v0.10.25
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! kafka-java-bridge@0.1.10 postinstall: `node ./scripts/postinstall.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the kafka-java-bridge@0.1.10 postinstall script 'node ./scripts/postinstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the kafka-java-bridge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/postinstall.js

**Comment by 1ManSmoking** [comment]
Hi bigbansal,

The issue is that child_process.execSync is only available from node v0.12 and up.
Please update node version and it will work for you.
Will update node version requirements in package.json.

BR,
Eli

**Comment by bigbansal** [comment]
Thanks!!!
