### ISSUE TITLE
Question: Why no producer?

### ISSUE THREAD

**Issue by ty10r** [LivePersonInc/kafka-java-bridge#7]
Hello,

I am evaluating replacing my `kafka-node` based implementation of a kafka consumer and a kafka producer.

As I have proof that the Java kafka client implementation is production ready, I'd like to move to this bridge.

Unfortunately, there is no HLProducer/Producer in this bridge.

I think it would be helpful for everyone considering contributing if we knew the difficulties of creating a bridge for the `kafka.clients.producer`.

Thanks for any help in advance.

**Comment by 1ManSmoking** [comment]
Hi,

I know we kind of neglected kafka-java-bridge lately.
Can promise producer by the end of the month.

BR,
Eli

**Comment by 1ManSmoking** [comment]
Implemented producer.
Sorry for the delay.

**Comment by ty10r** [comment]
@1ManSmoking No worries about the delay. The work is much appreciated :)
