### ISSUE TITLE
Annoying warning messages on start

### ISSUE THREAD

**Issue by TomDmitriev** [LivePersonInc/kafka-java-bridge#8]
> log4j:WARN No appenders could be found for logger (kafka.utils.VerifiableProperties).
log4j:WARN Please initialize the log4j system properly.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

How do I get rid of these? Can they be ignored? Do I need to configure logging for the Java part? If so, could you please explain how in the documentation?

**Comment by 1ManSmoking** [comment]
Hi,

Fixed.
By default java logging will be disabled.
If you wish, you can use your own log4j.properties file.
It has to be placed at:
{app root path}/kafka-java-bridge/log4j/log4j.properties
Documentation:
https://github.com/LivePersonInc/kafka-java-bridge#java-tier-logging

BR,
Eli

**Comment by TomDmitriev** [comment]
Thanks! I can confirm it is fixed in `v0.1.12`.
