### ISSUE TITLE
Getting topic/partition/offset

### ISSUE THREAD

**Issue by itamarwe** [LivePersonInc/kafka-java-bridge#9]
Is there a way to get the topic, partition and offset of a message?

**Comment by 1ManSmoking** [comment]
Hi,

No, it is currently not supported.
It makes a lot of sense to implement.
Next thing on the agenda is implementing producer next week.
Will try to find the time to implement message metadata afterward.

BR,
Eil

**Comment by itamarwe** [comment]
I actually quickly implemented it in a fork. If you like it we can expand it.
https://github.com/LivePersonInc/kafka-java-bridge/compare/master...itamarwe:feature_topicAndPartition

**Comment by 1ManSmoking** [comment]
Looking good at first glimpse.
But, we can skip sending the topic as we already have it in node tier.
And obviously will have to send the metadata as a second callback parameter so interface won't change for other users.
Will merge it into the code while writing the producer.

Thanks for contributing to the code.

**Comment by itamarwe** [comment]
Thanks.
I'm sending the topic for a couple of reasons:
1. Replicating the behavior of the popular Kafka node library.
2. Hoping to move forward to a multi topic consumer (or filtered topic consumer). I'm currently consuming ~100 topic simultaneously and managing the ports becomes a pain and an overhead.

Also, notice I'm committing the offsets before shutdown, so I won't lose the last offsets consumed.

**Comment by 1ManSmoking** [comment]
Hi,

Limiting the consumer to a single topic was probably a mistake.
It can easily be implemented as shown [here](https://cwiki.apache.org/confluence/display/KAFKA/Consumer+Group+Example).
As I'm going to work on the code sometime next week lets see what will I have time to add to it.
Implementing the producer and performance testing it still remains main issue.

Regarding committing the offsets after shutdown - it is unnecessary.
Also from same source: "Additionally, with auto commit enabled, the call to consumer.shutdown() will commit the final offsets".
We only support auto commit, so offset commitment is unnecessary.

**Comment by 1ManSmoking** [comment]
Implemented producer and added your code (with minor changes) to get consumed message metadata.
